inherit_from: ".rubocop.yml"

require:
  - rubocop-md

AllCops:
  Include:
    - '**/*.md'

# FIXME
Layout/InitialIndentation:
  Exclude:
    - 'CHANGELOG.md'

Lint/ConstantReassignment:
  Enabled: false
