name: Prism Build

on:
  push:
    branches:
    - master
  pull_request:
  workflow_dispatch:

jobs:
  prism-test:
    runs-on: ubuntu-latest
    env:
      BUNDLE_JOBS: 4
      BUNDLE_RETRY: 3
      CI: true
      PRISM: true
      STABLE_RUBY: true
    steps:
    - uses: actions/checkout@v4
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.4
        bundler-cache: true
    - name: Run MSpec
      run: |
        bundle exec bin/mspec :language
